[package]
name = "example-plugin"
version = "0.2.0"
authors = ["SOFe <sofe2038@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.33"
pocketmine = {path = "../rust"}
