[package]
name = "pocketmine"
version = "0.1.0"
authors = ["PMMP Team <team@pmmp.io>", "SOFe <sofe2038@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.33"
libc = "0.2.79"
once_cell = "1.4.1"
static_assertions = "1.1.0"

[build-dependencies]
bindgen = "0.55.1"

